"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fas29h=2hsu299h^7#t#3%=#)ein-%k1qia-ob5emem1)k@3(('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

'''
'템플릿' 에서 숫자에 '콤마' 붙이는 방법
step01 : settings.py 파일의 'INSTALLED_APPS' 영역에 앱 추가.
STEP02 : 'html 문서' 의 상단에 {% load humanize %} 코드 추가.
step03 : 'huml 문서' 에서 콤마를 표현하는 영역에서 템플릿 필터 추가.
    예시) 가격 : {{ product.price|intcomma }} 원
'''

# Application definition
#설치된 'App 현황 정보' 를 담고있는 'List' 입니다.
#주의) 'Developer' 가 앱을 생성 하고나면, 반드시, 등록을 해줘야 합니다.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'minitest.apps.MinitestConfig',  #'Developer' 가 생성한 앱 추가 ↓
    'member.apps.MemberConfig',
    'product.apps.ProductConfig',
    'django.contrib.humanize',  #'템플릿 필터' 에서, 숫자형 자료에 '콤마' 를 붙이기위해 추가함.
    'cart.apps.CartConfig',
    'order.apps.OrderConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

#'HTML 문서' 가 저장되는 'Template' 폴더를 지정 합니다.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#데이터가 저장이 될 '데이터베이스' 파일 이름을 지정합니다.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'cafe.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

#'한글 페이지' 를 보기 위해 '언어 코드' 와 '타임 존' 을 변경 합니다.
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ko-kr'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

#'MEDIA' 관련 정보
#MEDIA_URL : '브라우저' 에서 접근할때, 사용하는 'URL' 경로
MEDIA_URL = '/media/'

#MEDIA_ROOT : 사용자가 파일을 업로드하면, 물리적으로 파일이 저장되는 폴더
MEDIA_ROOT = BASE_DIR / 'media'
